// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<String> startGlobalListener() =>
    RustLib.instance.api.crateApiSimpleStartGlobalListener();

Future<bool> isAccessibilityPermissionGranted() =>
    RustLib.instance.api.crateApiSimpleIsAccessibilityPermissionGranted();

Future<void> sendEvent({
  required int eventType,
  required int value,
  double? mouseX,
  double? mouseY,
}) => RustLib.instance.api.crateApiSimpleSendEvent(
  eventType: eventType,
  value: value,
  mouseX: mouseX,
  mouseY: mouseY,
);
