// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String?> parseEventString({required String input}) =>
    RustLib.instance.api.crateApiUtilsParseEventString(input: input);

Future<Key> keyFromU32({required int value}) =>
    RustLib.instance.api.crateApiUtilsKeyFromU32(value: value);

Future<EventType?> eventTypeFromInt({
  required int eventType,
  required int value,
  double? mouseX,
  double? mouseY,
}) => RustLib.instance.api.crateApiUtilsEventTypeFromInt(
  eventType: eventType,
  value: value,
  mouseX: mouseX,
  mouseY: mouseY,
);

Future<Button> buttonFromU8({required int value}) =>
    RustLib.instance.api.crateApiUtilsButtonFromU8(value: value);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Button>>
abstract class Button implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EventType>>
abstract class EventType implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Key>>
abstract class Key implements RustOpaqueInterface {}
